spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/share?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    servlet:
      load-on-startup: 1
  redis:
    host: localhost
    port: 6379
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: xxx@163.com
    password: xxx
    protocol: smtp
    test-connection: false
  thymeleaf:
     cache: false
     prefix: classpath:/templates/
     suffix: .html
     encoding: UTF-8
     content-type: text/html
     mode: HTML5
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
mybatis:
  type-aliases-package: cn.artviewer.gallery.model
  mapper-locations: classpath:/mybatis-mappers/*

logging:
  config: classpath:logback-gallery.xml

server:
  port: 8086
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


